### ISSUE TITLE
API not returning the product stock

### ISSUE THREAD

**Issue by pks891618** [PrestaShop/PrestaShop-webservice-lib#67]
I am calling all products like this

/api/products?display=full&limit=0,10

But its not returning the stock

Is there is any possibilities to  show the stock quanity along with product details  ??

**Comment by matks** [comment]
Hello,

My apologies, it seems this repository was misconfigured. [A long time ago](https://build.prestashop-project.org/news/2018/moving-issues-to-github/) we decided to gather every problem about PrestaShop in the Core repository. For every problem, about every repository in the project, they should be put on the Core repository https://github.com/PrestaShop/prestaShop/ here: https://github.com/PrestaShop/PrestaShop/issues/new/choose

To enforce this, we closed the ability to open an issue on every other repository... but it seems we forgot this one. So nobody is checking this repository issues, because everybody checks issues on https://github.com/PrestaShop/PrestaShop/ not here :/

I will fix this by closing this repository "Issues" section and add a notice in the README.

As your issue is very old I prefer to close it and ask you to reopen one on https://github.com/PrestaShop/PrestaShop/ if it's still valid

Best regards,
