### ISSUE TITLE
API not returning Pack product chosen products/variations

### ISSUE THREAD

**Issue by lucaballerini** [PrestaShop/PrestaShop-webservice-lib#69]
When retrieving order details and a Pack product is purchased, API don't return specifications about products/variations in Pack product, in BO this is present in order details

**Comment by matks** [comment]
Hello,

My apologies, it seems this repository was misconfigured. [A long time ago](https://build.prestashop-project.org/news/2018/moving-issues-to-github/) we decided to gather every problem about PrestaShop in the Core repository. For every problem, about every repository in the project, they should be put on the Core repository https://github.com/PrestaShop/prestaShop/ here: https://github.com/PrestaShop/PrestaShop/issues/new/choose

To enforce this, we closed the ability to open an issue on every other repository... but it seems we forgot this one. So nobody is checking this repository issues, because everybody checks issues on https://github.com/PrestaShop/PrestaShop/ not here :/

I will fix this by closing this repository "Issues" section and add a notice in the README.

As your issue is very old I prefer to close it and ask you to reopen one on https://github.com/PrestaShop/PrestaShop/ if it's still valid

Best regards,
