### ISSUE TITLE
function edit (PUT) is broken

### ISSUE THREAD

**Issue by fansanelli** [PrestaShop/PrestaShop-webservice-lib#70]
Hello,

I think the edit function is broken... I cannot pass url + putXml due to the first condition:

```
        if (isset($options['url'])) {
            $url = $options['url'];
        } elseif ((isset($options['resource'], $options['id']) || isset($options['url'])) && $options['putXml']) {
```
please consider removing first 2 rows.
If you can accept a PR, please let me know

Cheers
Francesco

**Comment by aquiandres** [comment]
@fansanelli you only need to pass the URL once to edit a resource, this is when create an instance of the `PrestaShopWebservice` class. Once you created an object, you can edit at your will then call the `edit()` method to save any changes made on a given resource.

Consider this example:

```php
<?php

$PS_WS_URL = "http://localhost:8080/";
$PS_WS_KEY = "1234567890";
$PS_WS_DEBUG = false;

// FIRST: retrieve resource details
try {
    $ws = new PrestaShopWebservice($PS_WS_URL, $PS_WS_KEY, $PS_WS_DEBUG);
    $xml = $ws->get([
        'resource' => 'products',
        'id' => 1,
    ]);
} catch (PrestaShopWebserviceException $e) {
    printf("Error retrieving: %s\n", $e->getMessage());
}

// SECOND: make your changes here
$xml->product->price = "10000.00";

// THIRD: save your changes
try {
    $ws->edit([
        'resource' => 'products',
        'id' => 1,
        'putXml' => $xml->asXML(),
    ]);
    print("Price successfully updated!\n");
} catch (PrestaShopWebserviceException $e) {
    printf("Error saving: %s\n", $e->getMessage());
}
```

This is explained in the online [documentation](https://devdocs.prestashop.com/1.7/webservice/tutorials/prestashop-webservice-lib/update-resource/). This is all you need to do -- I hope so. If this still doesn't work for you, please explain a bit more about your scenario to better understand what are you trying to accomplish. I'm new working with this library but I'll try my best to help you -- if not then hopefully someone else will do.

**Comment by fansanelli** [comment]
Dear @aquiandres 

Your example has resource+id as arguments, but I'm passing just URL... So $xml will forever be empty.
Please compare with the add function to see what's wrong 😉.
Cheers,
Francesco

**Comment by aquiandres** [comment]
> Your example has resource+id as arguments, but I'm passing just URL... So $xml will forever be empty.

Yes, because if you want to update a resource you have to retrieve the details before saving by calling `edit()` and in my example I only want to "edit" a specific resource which is a product with 1 as an ID. If I wanted to create a new one, then I have to pass "url" as a param in `get()` and fill in the URL of the schema like this `$ws->get(['url' => 'http://example.com/api/products?schema=blank'])` and finally call `add()` to create a new resource passing in the corresponding params: `resource` and `postXml`.

![create-resource](https://user-images.githubusercontent.com/670551/86945581-3244ce00-c117-11ea-91e0-fba05da25e2b.png)

I think you are doing the wrong way. Just follow the correct workflow in order to successfully [create](https://devdocs.prestashop.com/1.7/webservice/tutorials/prestashop-webservice-lib/create-resource/#creation-workflow) or [update](https://devdocs.prestashop.com/1.7/webservice/tutorials/prestashop-webservice-lib/update-resource/#update-workflow) a resource.

**Comment by fansanelli** [comment]
Hi @aquiandres 
I think your missed my question... Please read check my patch, the code it's obliviously wrong
Thanks
Francesco

**Comment by leccyril** [comment]
Hello, 

can we edit an order in JSOn ? i have a vuejs3 dashboard, then i am retrieving an order and i want to update the status.... can we directly send the order object in JSON with axios ? because my application is in JS
thank you
if we can not how can we update or create an object from js application
thanks

**Comment by SlaVIc31** [comment]
Hi,
this problem still exists. 
I think PR #71 should be reopened.

**Comment by matks** [comment]
Hello everyone, [a long time ago](https://build.prestashop-project.org/news/2018/moving-issues-to-github/) we decided to gather every problem about PrestaShop in the Core repository. For every problem, about every repository in the project, they should be put on the Core repository https://github.com/PrestaShop/prestaShop/ here: https://github.com/PrestaShop/PrestaShop/issues/new/choose

To make sure it happens, we closed the ability to open an issue on every other repository... but it seems we forgot this one

I will fix this by closing this repository "Issues" section and add a notice in the README.

As your issue is very old I prefer to close it and ask you to reopen one on https://github.com/PrestaShop/PrestaShop/ if it's still valid

Best regards,
