### ISSUE TITLE
Add images support

### ISSUE THREAD

**Issue by fansanelli** [PrestaShop/PrestaShop-webservice-lib#72]
Hello,

this client does not support images, but it could with few changes...
1. avoid to call ParseXML
2. disallow debug functions for images

Would you accept a PR?

Thanks
Francesco

**Comment by wucherpfennig** [comment]
Would very much appreciate a PR...

**Comment by wa05** [comment]
Hi mate! you solved how to read images?

**Comment by matks** [comment]
Hello,

My apologies, it seems this repository was misconfigured. [A long time ago](https://build.prestashop-project.org/news/2018/moving-issues-to-github/) we decided to gather every problem about PrestaShop in the Core repository. For every problem, about every repository in the project, they should be put on the Core repository https://github.com/PrestaShop/prestaShop/ here: https://github.com/PrestaShop/PrestaShop/issues/new/choose

To enforce this, we closed the ability to open an issue on every other repository... but it seems we forgot this one. So nobody is checking this repository issues, because everybody checks issues on https://github.com/PrestaShop/PrestaShop/ not here :/ . This is why there was never an answer.

I will fix this by closing this repository "Issues" section and add a notice in the README.

Yes a PR would be welcomed - sorry for late response
