### ISSUE TITLE
output_format param for JSON doesn't work correctly in requests.

### ISSUE THREAD

**Issue by federicomasiero** [PrestaShop/PrestaShop-webservice-lib#75]
Following PrestaShop DevDocs I added output_format param into my request but doesn't work correctly and return still an XML.

`$webService->get([
                'resource' => 'orders',
                'limit' => '5',
                'display' => 'full',
                'sort' => 'id_DESC',
                'output_format' => 'JSON'
            ]);`

Debugging the request, the param output_format wasn't inserted into the URL string.

**Comment by LocalHeroPro** [comment]
```php
$xml = $webService->get(['resource' => '/?output_format=JSON']);
```
resulting
![image](https://user-images.githubusercontent.com/42643563/147883779-b1e3ccfb-6308-4d0f-a75a-0d4a39054d9a.png)

**Comment by federicomasiero** [comment]
Hi, @LocalHeroPro doesn't work because in the `get()` function there's this line that returns the result.
`return $this->parseXML($request['response']);`
As you can see an XML response is parsed, then the JSON response couldn't work properly.
Is a structural lack in the library.

**Comment by matks** [comment]
Hello,

My apologies, it seems this repository was misconfigured. [A long time ago](https://build.prestashop-project.org/news/2018/moving-issues-to-github/) we decided to gather every problem about PrestaShop in the Core repository. For every problem, about every repository in the project, they should be put on the Core repository https://github.com/PrestaShop/prestaShop/ here: https://github.com/PrestaShop/PrestaShop/issues/new/choose

To enforce this, we closed the ability to open an issue on every other repository... but it seems we forgot this one. So nobody is checking this repository issues, because everybody checks issues on https://github.com/PrestaShop/PrestaShop/ not here :/

I will fix this by closing this repository "Issues" section and add a notice in the README.

As your issue is very old I prefer to close it and ask you to reopen one on https://github.com/PrestaShop/PrestaShop/ if it's still valid

Best regards,
