### ISSUE TITLE
Search (filter) in two or more fields

### ISSUE THREAD

**Issue by simplygest** [PrestaShop/PrestaShop-webservice-lib#78]
Is it possible to search/filter, for example customers, which contains a value in BOTH FirstName and LastName, or even in Email?

AFAIK it is only possible to search/filter by ONE field at a time, or by more fields BUT as AND, not OR.

I need to search customers by firstname, lastname AND Email

**Comment by matks** [comment]
Hello,

My apologies, it seems this repository was misconfigured. [A long time ago](https://build.prestashop-project.org/news/2018/moving-issues-to-github/) we decided to gather every problem about PrestaShop in the Core repository. For every problem, about every repository in the project, they should be put on the Core repository https://github.com/PrestaShop/prestaShop/ here: https://github.com/PrestaShop/PrestaShop/issues/new/choose

To enforce this, we closed the ability to open an issue on every other repository... but it seems we forgot this one. So nobody is checking this repository issues, because everybody checks issues on https://github.com/PrestaShop/PrestaShop/ not here :/ so you never got an answer

Answer would be: if this feature is important for you, please submit a Pull Request to enable it.
